var knackModifiers = [
	"using the subtle art(s) of",
	"using a healthy dose of",
	"using the precise application of",
	"using the wayward ways of",
	"using the popularized form of",
	"using the secret ways of",
	"using the forbidden ways of",
	"using an arcane variant of",
	"using an adorably naive version of",
	"and all they have available to them is",
	"and they are going to try to do it using",
	"by wrongly using",
	"by using someone else's ",
	"by exploiting",
	"by relying on",
	"by correctly using",
	"by force, using only",
	"by the trusted use of",
	"using their guile as well as",
	"using what everyone already knows is just",
	"by secretly using",
	"without you relizing that they only have",
	"by incorrectly understanding",
	"using a perfect and exact knowledge of",
	"using the inherently enticing allure of",
	"with a most polite and considerate usage of",
	"using a terrible and underhaded form of",
	"using"
]