var knacks = [
	"Criminal connections",
	"Muscle",
	"Skill with a specific weapon",
	"Hedge wizardry",
	"Comprehensive local knowledge",
	"Noble blood",
	"A one-of-a-kind item",
	"Special destiny",
	"Unique perspective",
	"Hidden knowledge",
	"Magical awareness",
	"Abnormal parentage",
	"Political leverage",
	"A tie to a monster",
	"A secret",
	"True love",
	"An innocent heart",
	"A plan for the perfect crime",
	"A one-way ticket to paradise",
	"A mysterious ore",
	"Money, money, money",
	"A Divine blessing",
	"An Immunity from the law",
	"A Prophecy",
	"Secret martial arts techniques",
	"A ring of power",
	"A much-needed bag of taters",
	"A heart",
	"A fortified position",
	"Lawmaking",
	"Tongues",
	"A discerning eye",
	"Endurance",
	"A safe place",
	"Visions",
	"A beautiful mind",
	"A clear voice",
	"Stunning looks",
	"A catchy tune",
	"An Invention",
	"Baking",
	"Brewing",
	"Smelting",
	"Woodworking",
	"Writing",
	"An Immunity to fire",
	"Cooking",
	"Storytelling",
	"Ratcatching",
	"Lying",
	"Utter unremarkableness",
	"Mind-bending sexiness",
	"Undefinable coolness",
	"A way with knots",
	"Wheels of polished steel",
	"A magic carpet",
	"Endless ideas",
	"Persistance",
	"A stockpile of food",
	"A hidden path",
	"Piety",
	"Resistance to disease",
	"A Library",
	"A silver tongue",
	"Bloodline",
	"An innate spell",
	"Balance",
	"Souls",
	"Speed",
	"A sense of right and wrong",
	"Certainty",
	"An eye for detail",
	"Heroic self-sacrifice",
	"A Sense of direction",
	"A big idea",
	"A hidden entrance to the city",
	"The love of someone powerful",
	"Unquestioning loyalty",
	"Exotic fruit",
	"Poison",
	"Perfect memory",
	"The language of birds",
	"A key to an important door",
	"Metalworking",
	"Mysterious benefactors",
	"Steely nerves",
	"Bluffing",
	"A trained wolf",
	"A long-lost sibling, regained",
	"An arrow with your name on it",
	"A true name",
	"Luck",
	"The attention of supernatural powers",
	"Kindness",
	"Strange tatoos",
	"A magestic beard",
	"A book in a strange language",
	"Power overwhelming",
	"Delusions of granduer",
	"The wind at their back and a spring in their step."
]